#!/bin/bash

## Marge -- multifunction pdf archive script
## Revision 3.0 15-Feb-2024 21:14

## Requires incrond rclone ocrmypdf

## incrontab entry for user "scanner"
##   <$watchdir> IN_CLOSE_WRITE   /bin/bash /usr/local/sbin/marge $#

(
flock -n 9 || exit 1 
infilename=$@
timestamp=$(date "+%Y%m%d-%H%M%S")
incrondir="/var/cache/scanner"
tmpdir="/var/local/lib/scanner/.tmp"
tmpfile=".tmp_"$timestamp"_"$infilename
schooldir="/opt/shares/schoolwork"
schoolfile="LaurenHazlitt.Grade06.$timestamp.pdf"
uploaddir="eDocuments/SCANS"
documentfile="scan_"$timestamp".pdf"
ocrfile="ocr_"$timestamp".pdf"

sleep 2;
mv $incrondir/$@ $tmpdir/$tmpfile;
cd $tmpdir;
chmod 664 $tmpfile;

if [[ "$infilename" =~ "schoolwork_" ]]
then
    cp $tmpfile $schooldir/$schoolfile;
    chown lhaz:users $schooldir/$schoolfile;
    chmod 660 $schooldir/$schoolfile;
else
    ocrmypdf $tmpfile $ocrfile;
    sleep 5;
    rclone copy $ocrfile tkitzky@gmail.com:/$uploaddir;  
    sleep 2;
    rm $ocrfile;
fi

) 9>/run/lock/marge.lock
rm /run/lock/marge.lock
exit
